### PR TITLE
Realtime image after multiselect

### LINKED ISSUE #7: UI : Stub to display Real-time Traffic Image in the modal

### LINKED ISSUE #9: Data Pipeline: Set up configuration of REST API call to retrieve raw image based on camera id and time

### PR DESCRIPTION
**Pull request by gouruiyu**
Closing #9 
Closing #33 

Change based on #37 after multi-selection rework

### CODE REVIEW

**Review by nancywan1004 — COMMENTED** [review]
Works fine when only one camera is selected. :))
Suggestions:
- Can we prompt a message when there's no image available or multiple cameras are selected? Otherwise, it's a bit confusing to users.

**Comment by gouruiyu** [comment]
> Suggestions:
> 
> * Can we prompt a message when there's no image available or multiple cameras are selected? Otherwise, it's a bit confusing to users.

when there's no image available, the traffic explorer currently already says "the data for this camera is not available".
So if there's traffic explorer plot but no camera, it means multiple cameras are selected.

**Review by MartinYTSo — APPROVED** [review]
Everything is working on my local machine!

**Comment by nancywan1004** [comment]
> > Suggestions:
> > 
> > * Can we prompt a message when there's no image available or multiple cameras are selected? Otherwise, it's a bit confusing to users.
> 
> when there's no image available, the traffic explorer currently already says "the data for this camera is not available".
> So if there's traffic explorer plot but no camera, it means multiple cameras are selected.

Should we let the user know that they can only see the image when there is one camera selected? Otherwise, we'll display the current camera to avoid any confusion. Lmk what you think, otherwise lgtm.

**Comment by gouruiyu** [comment]
> > > Suggestions:
> > > 
> > > * Can we prompt a message when there's no image available or multiple cameras are selected? Otherwise, it's a bit confusing to users.
> > 
> > 
> > when there's no image available, the traffic explorer currently already says "the data for this camera is not available".
> > So if there's traffic explorer plot but no camera, it means multiple cameras are selected.
> 
> Should we let the user know that they can only see the image when there are multiple cameras selected? Otherwise, we'll display the current camera to avoid any confusion. Lmk what you think, otherwise lgtm.

tbh, I’m currently leaning towards having single selection and multi-selection mode separated using a user-controlled toggle, that way the workflow is much clearer as in the function of dropdown menu and camera image.
rn the dropdown menu lost its function, and whether to show camera image is also confusing.

**Review by nancywan1004 — APPROVED** [review]

**Pull request merged**
