### PR TITLE
added bike routes

### LINKED ISSUE #42: Visualize Bicycle Lanes

### PR DESCRIPTION
**Pull request by MartinYTSo**

### CODE REVIEW

**Comment by MartinYTSo** [comment]
Added bike routes:
Bike route file should be in the data folder 
image


User is able to toggle between on and off
image

**Comment by gouruiyu** [comment]
Can you also incorporate the information like BIKE_INFRASTRUCTURE_TYPE and STATUS?

**Comment by MartinYTSo** [comment]
Should I make a select Input feature where the use can filter based on BIKE_INFRASTRUCTURE_TYPE and STATUS?

**Comment by gouruiyu** [comment]
> Should I make a select Input feature where the use can filter based on BIKE_INFRASTRUCTURE_TYPE and STATUS?

I think different colors/shapes should be enough.

**Comment by MartinYTSo** [comment]
It looks like when I start up the app, the legend is hidden  and its automatically on
image

When I check the bike route on, it displays all the bike routes 
image

However, when I uncheck it again, the legend plus the bike route overlay dissapears.

image


Does anyone else have the same bug as I have ?

**Review by gouruiyu — CHANGES_REQUESTED** [review]
image
I have `bikeroutes_in_4326.geojson` in my data folder. Any other data is needed?

Please resolve merge conflicts too.

**Review by gouruiyu — CHANGES_REQUESTED** [review]
Can we make it floating at top left corner to avoid overlapping with the camera image?

**Review by gouruiyu — APPROVED** [review]
Approve for now. Please seek to fix the UI bug later.

**Review by nancywan1004 — APPROVED** [review]
Working for me too, except for the overlapping.

**Pull request merged**
