### PR TITLE
Adding customization for smoothing window size k

### PR DESCRIPTION
**Pull request by nancywan1004**

### CODE REVIEW

**Review by MartinYTSo — APPROVED** [review]
LGTM but would it be user friendly to add an error message if someone enters outside of the ranges 1 and 30?

image

**Comment by nancywan1004** [comment]
> LGTM but would it be user friendly to add an error message if someone enters outside of the ranges 1 and 30?
> 
> image

Made a fix for it. Could you test again to see if it makes sense to you?

**Comment by gouruiyu** [comment]
Error handling is working for me =)
Two UI things:
- ending bracket
image
- Can we make the UI more compressed? For example just "smoothing window size" with a fix width box, all inline. Now the input box stretches when you resize the panel, and the UI seems a bit too heavy with it.

**Comment by MartinYTSo** [comment]
LGTM!

**Review by gouruiyu — APPROVED** [review]

**Pull request merged**
