### PR TITLE
Realtime image after API is updated

### PR DESCRIPTION
**Pull request by gouruiyu**
Behavior is same as previous, except now it should fetch the actual real-time camera image.

### CODE REVIEW

**Review by nancywan1004 — APPROVED** [review]
Lgtm!

**Review by MartinYTSo — COMMENTED** [review]
image

For some reason it crashed  on me and it gave me this error. I downloaded the new API and cleared my existing variables but it still didn't work

**Comment by gouruiyu** [comment]
> image
> 
> For some reason it crashed on me and it gave me this error. I downloaded the new API and cleared my existing variables but it still didn't work

Weird, `prepend()` was introduced in #40, and it came with R base library so should work fine.
And this PR does not introduce any new library, nor change any code in UI around `prepend()`'s usage.
@nancywan1004 Have you ever seen this error message?
@MartinYTSo Would you mind try clearing the local, restart, pull to make sure its a clean copy and retry?

**Comment by nancywan1004** [comment]
> > image
> > For some reason it crashed on me and it gave me this error. I downloaded the new API and cleared my existing variables but it still didn't work
> 
> Weird, `prepend()` was introduced in #40, and it came with R base library so should work fine.
> And this PR does not introduce any new library, nor change any code in UI around `prepend()`'s usage.
> @nancywan1004 Have you ever seen this error message?
> @MartinYTSo Would you mind try clearing the local, restart, pull to make sure its a clean copy and retry?

I don't see this error though. Could you reload the libraries and see if it works @MartinYTSo ? Also not sure if we need to introduce new libraries for prepend. This may be subject to differences on different machines?

**Comment by gouruiyu** [comment]
> > > image
> > > For some reason it crashed on me and it gave me this error. I downloaded the new API and cleared my existing variables but it still didn't work
> > 
> > 
> > Weird, `prepend()` was introduced in #40, and it came with R base library so should work fine.
> > And this PR does not introduce any new library, nor change any code in UI around `prepend()`'s usage.
> > @nancywan1004 Have you ever seen this error message?
> > @MartinYTSo Would you mind try clearing the local, restart, pull to make sure its a clean copy and retry?
> 
> I don't see this error though. Could you reload the libraries and see if it works @MartinYTSo ? Also not sure if we need to introduce new libraries for prepend. This may be subject to differences on different machines?

Could be Rlang version. It is included at least in `rlang (version 0.2.2)`, worth checking. @MartinYTSo

**Comment by gouruiyu** [comment]
Issue not relevant with this PR, continued in #49. 
Merging this.

**Pull request merged**
