### PR TITLE
Heatmap fix

### PR DESCRIPTION
**Pull request by MartinYTSo**
image

Heatmap can only render within a one hour period. On the side panel, you are able to switch between cam map and heatmap

### CODE REVIEW

**Review by nancywan1004 — COMMENTED** [review]
LGTM! One minor thing - maybe change the heatmap's tabItem icon to a different one than Cam Map?

**Comment by MartinYTSo** [comment]
image

**Review by nancywan1004 — COMMENTED** [review]
The new icon looks great. Sorry just noticed and forgot to mention that, could you also set the default map view to include and center at the entire Surrey? Right now it's zoomed at a weird spot as I first open the page.

**Comment by MartinYTSo** [comment]
Yes. This is  because if the map is set to the view like in the original basemap, the user cannot see the full change in pattern of the heatmap

**Comment by nancywan1004** [comment]
> Yes. This is because if the map is set to the view like in the original basemap, the user cannot see the full change in pattern of the heatmap

Okay so is this something you are going to fix? Since we want the user to see the overall change by default. 
Also, just found another small bug - right now the heatmap's time slider will show when I click on the help tab.

**Comment by gouruiyu** [comment]
Having the same issue as before. 
image
Have you found out which package is causing this issue?

**Comment by MartinYTSo** [comment]
The error was actually in my heatmap_function.R. When I removed lines 22-39. Other than that, I recommend you to  restart  R and remove your environmental variables

**Review by nancywan1004 — COMMENTED** [review]
Looks much better now! But could you also show the heatmap when the user first opens up the page? Now it's kinda confusing as nothing shows up unless you click on the play button. Maybe you could just use the default state?

**Comment by MartinYTSo** [comment]
Hmm, it used to appears to work when I set the max to a number in the heatmap arguments. If I do that though, there is no guarantee that the number I set will be the maximum number in future dataframes... Should I just make a note of it in the help section instead?

**Comment by nancywan1004** [comment]
> Hmm, it used to appears to work when I set the max to a number in the heatmap arguments. If I do that though, there is no guarantee that the number I set will be the maximum number in future dataframes... Should I just make a note of it in the help section instead?

Couldn't you add a heatmap in your baseHeatmap then? And remove it and add a new one on time slider's change?

**Comment by MartinYTSo** [comment]
Okay  it should work now, I was comparing a clean version of a heatmap vs the version I am working on now and it didnt have the default heatmap under the old version's ``basemap``... Thanks for your suggestion!

**Review by nancywan1004 — DISMISSED** [review]
LGTM now. :) No more feedback unless @Ein04 has anything else.

**Comment by gouruiyu** [comment]
The one-hour view lgtm. If it is only for one-hour, I think it makes more sense to just disable user from adjust the time slider to include more than an hour. Or, just make it a time point, and under the hood it takes it as the nearest hour.
In other words, I don't see a need to make the time internal adjustable.

**Comment by gouruiyu** [comment]
@MartinYTSo @nancywan1004  
Put a hacky fix to disable user from adjusting the range (it's a value instead of range now)
Also changed the step to 3600 seconds = 1 hour instead so the animation would not be inconsistent.
Adjust max to avoid the following error. In previous version it occurs when you drag or play animation until the end of the slider.
image

**Review by nancywan1004 — APPROVED** [review]
LGTM and thanks for the fix! :))

**Pull request merged**
