### PR TITLE
Adding vehicleType selectInput and time slider

### LINKED ISSUE #5: Line plot: user selected vehicle type
Have the line plot be dynamic depending on user-selected values on different vehicle type.

### PR DESCRIPTION
**Pull request by nancywan1004**
What:
Adding UI components for vehicleType selectInput and time slider

### CODE REVIEW

**Review by MartinYTSo — APPROVED** [review]
Everything is running on my machine!

**Comment by gouruiyu** [comment]
image
Slider and vehicleType selectInput work! Except the line plot seems to be gone for me :0 wonder if I'm missing something...

**Comment by nancywan1004** [comment]
> image
> Slider and vehicleType selectInput work! Except the line plot seems to be gone for me :0 wonder if I'm missing something...

I guess you need to click on the camera marker to see the line plot. Is it what you see when you firstly launch the app?

**Comment by MartinYTSo** [comment]
When I first launch the app, there is not plot on the sidebar. However, when I clicked a camera, it shows the line plot. Is that for everyone else?

**Review by MartinYTSo — DISMISSED** [review]
When I first launch the app, there is not plot on the sidebar. However, when I clicked a camera, it shows the line plot. Is that for everyone else? Otherwise that's good on my end

**Comment by nancywan1004** [comment]
> image
> Slider and vehicleType selectInput work! Except the line plot seems to be gone for me :0 wonder if I'm missing something...

Screen Shot 2021-07-15 at 11 35 38 AM

I'm not able to reproduce it on my end though.

**Comment by gouruiyu** [comment]
One minor suggestion: Can we make the time slider draggable and by default shows up somewhere without covering the zoom buttons?
Other than that it looks fine on my end!

**Comment by Ein04** [comment]
Working on my end! :D
Also the autoplay is super cool! Nice work :)

**Review by gouruiyu — APPROVED** [review]
Working on my end! :D
Also the autoplay is super cool! Nice work :)

**Comment by MartinYTSo** [comment]
Just saw the new changes, its also working on my end.

**Review by MartinYTSo — APPROVED** [review]
Its working on my end!

**Pull request merged**
