### PR TITLE
Adding paired camera's AM/PM car count bias analysis

### LINKED ISSUE #21: Feature: Data Analysis Side

### PR DESCRIPTION
**Pull request by nancywan1004**

### CODE REVIEW

**Review by MartinYTSo — COMMENTED** [review]
Heres a very minor change, you want to put ``library(nngeo)`` on the top of your library list because it threw me an error that I have no packages called ``nngeo``. I had to install it before running it

Edit: neverminded. LGTM!, I forgot you had another file. I think you have some conflicts though

**Review by MartinYTSo — DISMISSED** [review]
Looks good on my end. Just resolve those conflicts on app.R and you will be good to go!

**Review by gouruiyu — DISMISSED** [review]
image
Was this part of UI necessary?  
I also have some questions regarding the check of the nearest cameras, some cameras do not pass the criteria even though they are close. But I think it looks good for now and we can refine by adding About/Help text/tooltips later.

**Comment by nancywan1004** [comment]
> image
> 
> Was this part of UI necessary? I also have some questions regarding the check of the nearest cameras, some cameras do not pass the criteria even though they are close. But I think it looks good for now and we can refine by adding About/Help text/tooltips later.

Yeah I'll make more follow-up UI changes later. Considering this is a big change, I'll try to merge first for now. :))

**Review by gouruiyu — APPROVED** [review]
Pulled the latest version and LGTM!

**Pull request merged**
