### PR TITLE
Implementing layer control for Nearby Cams and hooking with the line…

### LINKED ISSUE #18: Biz: Select certain business site and highlight nearby cameras
This is a recommended feature from Dave.
I suggested the following feature behaviour:
Once a business marker is selected, the user should be able to choose a customized radius. Nearby cameras within that radius should be highlighted, and our vehicle count modal should show the aggregated count of those cameras.

This would depend on the feature #17.

Let me know what you guys think @MartinYTSo @nancywan1004

### PR DESCRIPTION
**Pull request by nancywan1004**
… plot

### CODE REVIEW

**Review by gouruiyu — COMMENTED** [review]
image
Currently, if nearest cameras are selected it will not add the user selected one to the line plot. Should we allow users to select more cameras outside the nearest three?

**Comment by nancywan1004** [comment]
> image
> 
> Currently, if nearest cameras are selected it will not add the user selected one to the line plot. Should we allow users to select more cameras outside the nearest three?

I thought we only want to display the nearby cameras. If the user wants to see the selected cameras only, they should uncheck the "Nearby Cams" layer on the bottom right. Say if the selected cameras and the nearby cameras are very far away, I don't think it's a good idea to keep them both in the plot.

**Comment by gouruiyu** [comment]
> > image
> > Currently, if nearest cameras are selected it will not add the user selected one to the line plot. Should we allow users to select more cameras outside the nearest three?
> 
> I thought we only want to display the nearby cameras. If the user wants to see the selected cameras only, they should uncheck the "Nearby Cams" layer on the bottom right. Say if the selected cameras and the nearby cameras are very far away, I don't think it's a good idea to keep them both in the plot.

What if there are 4 nearest cameras and the user would like to add the last one to the visual too?

**Comment by nancywan1004** [comment]
> > > image
> > > Currently, if nearest cameras are selected it will not add the user selected one to the line plot. Should we allow users to select more cameras outside the nearest three?
> > 
> > 
> > I thought we only want to display the nearby cameras. If the user wants to see the selected cameras only, they should uncheck the "Nearby Cams" layer on the bottom right. Say if the selected cameras and the nearby cameras are very far away, I don't think it's a good idea to keep them both in the plot.
> 
> What if there are 4 nearest cameras and the user would like to add the last one to the visual too?

Hmm, right now the default is 3, which could be customizable. But that shouldn't interfere with the selected cameras?

**Comment by MartinYTSo** [comment]
I've also noticed that the camera selected is capped at 3. If I, say selected 5 cameras, the graph does not update to the 5 cameras selected. Is this something that can be added? Selecting more than 3 cameras and updating the graph to more than 3 line plots?

image

**Comment by gouruiyu** [comment]
> > > > image
> > > > Currently, if nearest cameras are selected it will not add the user selected one to the line plot. Should we allow users to select more cameras outside the nearest three?
> > > 
> > > 
> > > I thought we only want to display the nearby cameras. If the user wants to see the selected cameras only, they should uncheck the "Nearby Cams" layer on the bottom right. Say if the selected cameras and the nearby cameras are very far away, I don't think it's a good idea to keep them both in the plot.
> > 
> > 
> > What if there are 4 nearest cameras and the user would like to add the last one to the visual too?
> 
> Hmm, right now the default is 3, which could be customizable. But that shouldn't interfere with the selected cameras?

For me it is kinda counter-intuitive to have the selection remain enabled but line plot detached at the same time 🧐. But it's minor UX stuff, will approve for now 🤓

**Review by gouruiyu — APPROVED** [review]

**Review by MartinYTSo — APPROVED** [review]
Ok then I guess we can approve it and make a note out of it in the help section?

**Pull request merged**
