### PR TITLE
Realtime image

### LINKED ISSUE #7: UI : Stub to display Real-time Traffic Image in the modal

### LINKED ISSUE #9: Data Pipeline: Set up configuration of REST API call to retrieve raw image based on camera id and time

### PR DESCRIPTION
**Pull request by gouruiyu**
https://user-images.githubusercontent.com/17880059/126243819-d356a62a-12fb-4955-977f-d1da567ce295.mov

### CODE REVIEW

**Review by MartinYTSo — COMMENTED** [review]
image

There's an error in a few cameras I selected

**Comment by gouruiyu** [comment]
> image
> 
> There's an error in a few cameras I selected

May I have one example camera id? Probably due to their API returning 200 even when retrieval failed. Just got an update from Dave yesterday night and I should be able to put up a quick fix.

**Comment by MartinYTSo** [comment]
Here is an example camera ID: enc_no10_kgbv_cam1

**Review by nancywan1004 — COMMENTED** [review]
I'm also seeing the error Martin mentioned. Here's an example with its camera id.

Screen Shot 2021-07-20 at 11 25 04 AM

**Comment by gouruiyu** [comment]
Closed due to structure change in dev/branch
Work continue in #41

**Pull request closed without merging**
